---
title: "DingQinTuto4"
author: "Ding Qin"
date: "Wednesday, February 17, 2016"
output: md_document
---

(a)  Is there any difference in complication rates between patients with good diabetic control and those with poor control?

     Complication rate (good) = 3/10 = 30%; 
     Complication rate (poor) = 4/6 = 66.7%; 
     Odd rates = (3/7)/(4/2) = 0.21
     
     There is difference in complication rates between patients with good diabetic control and those with poor control.

(b)  Determine whether the difference between the two rates is statistically different?
     
```{r}
dia = matrix(c(3,4,7,2), nr=2, dimnames=list(c("Good", "Poor"), c("Present", "Absent")))
fisher.test(dia)
```

From the fisher's test result above we can see that the p-value > 0.05, which indicates that the two rates is not statistically different.

(c)  Explain why the chi-square test should not be used for this study.

     Chi-square test is used to determine whether there is a significant association between the two variables, namely diabetic control and diabetic complications in this case. It is more suitable for sample size that is large. It should be used when the following conditions are met:
      -	The sampling method is simple random sampling.
      -	The variables under study are each categorical.
      -	If sample data are displayed in a contingency table, the expected frequency count for each cell of the table is at least 5.

Since in this case the sample size is small, and we cannot infer from the question whether the 16 patients are selected using simple random sampling, and only the frequency count for patients with diabetic complications absent under good diabetic control is at least 5, chi-square test should not be used for this study.
